### ISSUE TITLE
How can i manually set the alignment?

### ISSUE THREAD

**Issue by n-for-all** [calmcom/SexyTooltip#8] opened 2018-07-29 08:18 UTC
The auto alignment is very nice however it doesn't make sense, if the text is on the left the tooltip pops up in the middle, if you add a view left to the text to force the tooltip to be on the left, the edge of the screen covers the tooltip.

![image](https://user-images.githubusercontent.com/171367/43364312-cbd61a8e-9328-11e8-8db4-fb7c17980bc0.png)

![image](https://user-images.githubusercontent.com/171367/43364340-644920fe-9329-11e8-83eb-a0f956b3c6cb.png)

we need a possible way to force the tooltip to be on the left, i.e only 2 positions are allowed to change, up and down with the arrow pointing exactly to the start of the view.

is this possible somehow, manual alignment?

**Comment by tsheaff** [comment] 2018-07-29 16:10
@n-for-all can you post your code? I think what you need is to change the `inView`. Something like

```
[tooltip presentFromView:self.emailForm
                  inView:self.emailFormContainer];
```

See the second gif in the project readme and notice how the tooltip always stays visible within the boundaries.

**Comment by n-for-all** [comment] 2018-07-29 20:04
yes, it works if you have a width on the element you are displaying the tooltip for, however to force the tooltip to display on the left, i created an empty label of width 1px before the input exactly, instead of adjusting and the arrow moving to the left or the right like the gif, the whole tooltip moved outside the screen.

the code is basically simple, an input, a 1px label before the input.

[tooltip presentFromView:self.dummyLabel inView:self.view withMargin:10 animated:YES];

i tried all the codes in the readme, all works the same.

**Comment by tsheaff** [comment] 2018-07-29 20:19
Why don't you have a width available to you? Not sure I understand the usefulness of the 1px experiment.

A sample project with a minimal reproducing bug would be helpful. We've used tooltips extensively in our app with millions of users in production at Calm but never seen an issue like this, so Im confident there's a way to avoid it with a simple change

**Comment by tsheaff** [comment] 2018-07-29 20:21
You can also put breakpoints inside SexyTooltip.m's code that determines the positioning of the tooltip and see what cas it's getting into.

I know if the size of the inView is too small to fit the tooltip the behavior is undetermined. What is the frame of self.view when you present the tooltip?

**Comment by n-for-all** [comment] 2018-07-30 06:26
![image](https://user-images.githubusercontent.com/171367/43380583-bbb1f3ca-93e2-11e8-883e-65835e8c8c90.png)
![image](https://user-images.githubusercontent.com/171367/43380661-f27ce248-93e2-11e8-9634-a8a33c346730.png)

let me know

**Comment by tsheaff** [comment] 2018-07-30 16:12
Ok so teh question is why is the x = -73.5? It should fit it into the inView. What is the frame of the inView? Is it too small to fit the tooltip?

**Comment by tsheaff** [comment] 2018-07-30 16:18
Oh Ok I missed the first pic. It looks like the height of bounds is too small to fit the tooltip vertically. If the bounds arent >= the size of the tooltip, the behavior is undeterministic (it cannot find a place to fit the tooltip when it doesnt fit)

Try an inView that is the size of the UIWindow (you could even use the UIWindow itself)

**Comment by tsheaff** [comment] 2018-07-30 16:22
Note that NSLog indicating that it couldnt fit.

Im gonna close this out.

**Closed as completed** 2018-07-30 16:22 UTC

**Comment by tsheaff** [comment] 2018-07-30 16:24
I could add “The inView’s bounds.size must be larger than the ultimate bounds.size of the tooltip, otherwise there will be no way to place the tooltip” to the README

**Comment by n-for-all** [comment] 2018-08-01 07:47
I am not sure i am following you here, whether the height or the width is smaller or bigger, the fit should be based on the screen and there is always a place to fit, unless the view is full screen.

plus why are you following the height and width of the view, why not only the position of the view and display the tooltip based on that position and the max amount of space relative to the screen.

**Comment by tsheaff** [comment] 2018-08-01 13:41
When you present the tooltip you're specifying the fromView and inView. The fromView is the one the tooltip will always be pointing at, regardless of how thatview moves (like in the README gif). The inView though is the container view that the tooltip stays inside of and never moves outside of. So it by definition must be bigger than the tooltip itself.

Just try passing the UIWindow as inView and see what happens
